#include <cinttypes>
#include <cstddef>
#include <cstdio>

int main() {
  char const *const names[] = {
    "Bahamas — March On, Bahamaland"                                                ".txt",
    "Bahrain — Our Bahrain"                                                         ".txt",
    "Bangladesh — Amar Shonar Bangla"                                               ".txt",
    "Barbados — In Plenty and In Time of Need"                                      ".txt",
    "Belarus — My Belarusy"                                                         ".txt",
    "Belgium — The Brabançonne"                                                     ".txt",
    "Belize — Land of the Free"                                                     ".txt",
    "Benin — L'Aube Nouvelle"                                                       ".txt",
    "Bhutan — Druk Tsendhen"                                                        ".txt",
    "Bolivia — Himno Nacional de Bolivia"                                           ".txt",
    "Bosnia and Herzegovina"                                                        ".txt",
    "Botswana — Fatshe leno la rona"                                                ".txt",
    "Brazil — Hino Nacional Brasileiro"                                             ".txt",
    "Brunei — Allah Peliharakan Sultan"                                             ".txt",
    "Bulgaria — Mila Rodino"                                                        ".txt",
    "Burkina Faso"                                                                  ".txt",
    "Une Seule Nuit"                                                                ".txt",
    "Burundi — Burundi Bwacu"                                                       ".txt",
    "Cambodia — Nokoreach"                                                          ".txt",
    "Cameroon"                                                                      ".txt",
    "Canada — O Canada"                                                             ".txt",
    "Cape Verde — Cântico da Liberdade"                                             ".txt",
    "Central African Republic"                                                      ".txt",
    "Chad — La Tchadienne"                                                          ".txt",
    "Chile — Himno Nacional de Chile"                                               ".txt",
    "China — Yìyǒngjūn Jìnxíngqǔ"                                                   ".txt",
    "Colombia — Himno Nacional de la República de Colombia"                         ".txt",
    "Comoros — Udzima wa ya Masiwa"                                                 ".txt",
    "Democratic Republic of the Congo — Debout Congolais"                           ".txt",
    "Republic of the Congo — La Congolaise"                                         ".txt",
    "Costa Rica — Himno Nacional de Costa Rica"                                     ".txt",
    "Croatia — Lijepa naša domovino"                                                ".txt",
    "Cuba — El Himno de Bayamo"                                                     ".txt",
    "Cyprus — Ýmnos eis tīn Eleutherían"                                            ".txt",
    "Czech Republic — Kde domov můj"                                                ".txt",
    "Denmark — Der er et yndigt land"                                               ".txt",
    "Denmark — Kong Christian stod ved højen mast"                                  ".txt",
    "Djibouti — Djibouti"                                                           ".txt",
    "Dominica — Isle of Beauty, Isle of Splendour"                                  ".txt",
    "Dominican Republic — Himno Nacional"                                           ".txt",
    "East Timor — Pátria"                                                           ".txt",
    "Ecuador — Salve, Oh Patria"                                                    ".txt",
    "Egypt — Bilady, Bilady, Bilady"                                                ".txt",
    "El Salvador — Himno Nacional de El Salvador"                                   ".txt",
    "Equatorial Guinea — Caminemos pisando las sendas de nuestra inmensa felicidad" ".txt",
    "Eritrea — Ertra, Ertra, Ertra"                                                 ".txt",
    "Estonia — Mu isamaa, mu õnn ja rõõm"                                           ".txt",
    "Eswatini — Nkulunkulu Mnikati wetibusiso temaSwati"                            ".txt",
    "Ethiopia — Wodefit Gesgeshi, Widd Innat Ityopp'ya"                             ".txt",
    "Fiji — Meda Dau Doka"                                                          ".txt",
    "Finland — Maamme"                                                              ".txt",
    "France — La Marseillaise"                                                      ".txt",
    "Gabon — La Concorde"                                                           ".txt",
    "The Gambia — For The Gambia Our Homeland"                                      ".txt",
    "Georgia — Tavisupleda"                                                         ".txt",
    "Germany — Lied der Deutschen"                                                  ".txt",
    "Ghana — God Bless Our Homeland Ghana"                                          ".txt",
    "Greece — Ýmnos eis tīn Eleutherían"                                            ".txt",
    "Grenada — Hail Grenada"                                                        ".txt",
    "Guatemala — Himno Nacional de Guatemala"                                       ".txt",
    "Guinea — Liberté"                                                              ".txt",
    "Guinea-Bissau"                                                                 ".txt",
    "Guyana — Dear Land of Guyana, of Rivers and Plains"                            ".txt",
    "Haiti — La Dessalinienne"                                                      ".txt",
    "Honduras — Himno Nacional de Honduras"                                         ".txt",
    "Hungary — Himnusz"                                                             ".txt",
    "Iceland — Lofsöngur"                                                           ".txt",
    "India — Jana Gana Mana"                                                        ".txt",
    "Indonesia — Indonesia Raya"                                                    ".txt",
    "Iran — Mehre Khâvarân"                                                         ".txt",
    "Iraq — Mawtini"                                                                ".txt",
    "Ireland — Amhrán na bhFiann"                                                   ".txt",
    "Israel — HaTikvah"                                                             ".txt",
    "Italy — Il Canto degli Italiani"                                               ".txt",
    "Ivory Coast"                                                                   ".txt",
    "Jamaica — Jamaica, Land We Love"                                               ".txt",
    "Japan — Kimi ga Yo"                                                            ".txt",
    "Jordan — Al-salam Al-malaki Al-urdoni"                                         ".txt",
    "Kazakhstan — Meniñ Qazaqstanım"                                                ".txt",
    "Kenya — Ee Mungu Nguvu Yetu"                                                   ".txt",
    "Kiribati — Teirake Kaini Kiribati"                                             ".txt",
    "North Korea"                                                                   ".txt",
    "South Korea — Aegukga"                                                         ".txt",
    "Kuwait — Al-Nasheed Al-Watani"                                                 ".txt",
    "Kyrgyzstan — Kyrgyz Respublikasynyn Mamlekettik Gimni"                         ".txt",
    "Laos — Pheng Xat Lao"                                                          ".txt",
    "Latvia — Dievs, svētī Latviju!"                                                ".txt",
    "Lebanon — Lebanese National Anthem"                                            ".txt",
    "Lesotho — Lesotho Fatše La Bontata Rona"                                       ".txt",
    "Liberia — All Hail, Liberia, Hail!"                                            ".txt",
    "Libya — Libya, Libya, Libya!"                                                  ".txt",
    "Liechtenstein — Oben am jungen Rhein"                                          ".txt",
    "Lithuania — Tautiška giesmė"                                                   ".txt",
    "Luxembourg — Ons Heemecht"                                                     ".txt",
    "Madagascar — Ry Tanindrazanay malala ô!"                                       ".txt",
    "Malawi — Mulungu dalitsa Malaŵi"                                               ".txt",
    "Malaysia — Negaraku"                                                           ".txt",
    "Maldives — Gaumii salaam"                                                      ".txt",
    "Mali — Le Mali"                                                                ".txt",
    "Malta — L-Innu Malti"                                                          ".txt",
    "Marshall Islands — Forever Marshall Islands"                                   ".txt",
    "Mauritania — Bilada-l ubati-l hudati-l kiram"                                  ".txt",
    "Mauritius — Motherland"                                                        ".txt",
    "Mexico — Himno Nacional Mexicano"                                              ".txt",
    "Micronesia — Patriots of Micronesia"                                           ".txt",
    "Moldova — Limba noastră"                                                       ".txt",
    "Monaco — Hymne Monégasque"                                                     ".txt",
    "Mongolia"                                                                      ".txt",
    "Montenegro — Oj, svijetla majska zoro"                                         ".txt",
    "Morocco — Cherifian Anthem"                                                    ".txt",
    "Mozambique — Pátria Amada"                                                     ".txt",
    "Myanmar"                                                                       ".txt",
    "Namibia"                                                                       ".txt",
    "Nauru — Nauru Bwiema"                                                          ".txt",
    "Nepal — Sayaun Thunga Phulka"                                                  ".txt",
    "Netherlands — The Wilhelmus"                                                   ".txt",
    "New Zealand — God Defend New Zealand"                                          ".txt",
    "New Zealand — God Save the King"                                               ".txt",
    "Nicaragua — Salve a ti, Nicaragua"                                             ".txt",
    "Niger — L'Honneur de la Patrie"                                                ".txt",
    "Nigeria — Nigeria, We Hail Thee"                                               ".txt",
    "North Macedonia — Denes nad Makedonija"                                        ".txt",
    "Norway — Ja, vi elsker dette landet"                                           ".txt",
    "Oman — Nashid as-Salaam as-Sultani"                                            ".txt",
    "Pakistan — Qaumī Tarāna"                                                       ".txt",
    "Palau — Belau rekid"                                                           ".txt",
    "Palestine"                                                                     ".txt",
    "Panama — Himno Istmeño"                                                        ".txt",
    "Papua New Guinea — O Arise, All You Sons"                                      ".txt",
    "Paraguay — Paraguayos, República o Muerte"                                     ".txt",
    "Peru — Himno Nacional del Perú"                                                ".txt",
    "Philippines — Lupang Hinirang"                                                 ".txt",
    "Poland — Mazurek Dąbrowskiego"                                                 ".txt",
    "Portugal — A Portuguesa"                                                       ".txt",
    "Qatar — As Salam Al Amiri"                                                     ".txt",
    "Romania — Deșteaptă-te, române!"                                               ".txt",
    "Russia — Gosudarstvenny Gimn Rossiyskoy Federatsii"                            ".txt",
    "Rwanda — Rwanda Nziza"                                                         ".txt",
    "Saint Kitts and Nevis — O Land of Beauty!"                                     ".txt",
    "Saint Lucia — Sons and Daughters of Saint Lucia"                               ".txt",
    "Saint Vincent and the Grenadines — Saint Vincent, Land so Beautiful"           ".txt",
    "Samoa — The Banner of Freedom"                                                 ".txt",
    "San Marino — Inno Nazionale della Repubblica"                                  ".txt",
    "São Tomé and Príncipe — Independência total"                                   ".txt",
    "Saudi Arabia — As-Salam Al Malaki"                                             ".txt",
    "Senegal — Pincez tous vos koras, frappez les balafons"                         ".txt",
    "Serbia — Bože pravde"                                                          ".txt",
    "Seychelles — Koste Seselwa"                                                    ".txt",
    "Sierra Leone — High We Exalt Thee, Realm of the Free"                          ".txt",
    "Singapore — Majulah Singapura"                                                 ".txt",
    "Slovakia — Nad Tatrou sa blýska"                                               ".txt",
    "Slovenia — Zdravljica"                                                         ".txt",
    "Solomon Islands — God Save Our Solomon Islands"                                ".txt",
    "Somalia — Qolobaa Calankeed"                                                   ".txt",
    "South Africa — National Anthem of South Africa"                                ".txt",
    "South Sudan — South Sudan Oyee!"                                               ".txt",
    "Spain — La Marcha Real"                                                        ".txt",
    "Sri Lanka — Sri Lanka Matha"                                                   ".txt",
    "Sudan — Nahnu Jund Allah Jund Al-watan"                                        ".txt",
    "Suriname — God zij met ons Suriname"                                           ".txt",
    "Sweden — Du gamla, du fria"                                                    ".txt",
    "Switzerland — Schweizerpsalm"                                                  ".txt",
    "Syria — Humāt ad-Diyār"                                                        ".txt",
    "Tajikistan — Surudi Milli"                                                     ".txt",
    "Tanzania — Mungu ibariki Afrika"                                               ".txt",
    "Thailand — Phleng Chat"                                                        ".txt",
    "Togo — Salut à toi, pays de nos aïeux"                                         ".txt",
    "Tonga — Ko e fasi ʻo e tuʻi ʻo e ʻOtu Tonga"                                   ".txt",
    "Trinidad and Tobago — Forged from the Love of Liberty"                         ".txt",
    "Tunisia — Humat al-Hima"                                                       ".txt",
    "Turkey — İstiklâl Marşı"                                                       ".txt",
    "Turkmenistan — Türkmenbaşyň guran beýik binasy"                                ".txt",
    "Tuvalu — Tuvalu mo te Atua"                                                    ".txt",
    "Uganda — Oh Uganda, Land of Beauty"                                            ".txt",
    "Ukraine — Shche ne vmerla Ukrainy"                                             ".txt",
    "United Arab Emirates — Ishy Bilady"                                            ".txt",
    "United Kingdom — God Save the King"                                            ".txt",
    "United States — The Star-Spangled Banner"                                      ".txt",
    "Uruguay — Himno Nacional"                                                      ".txt",
    "Uzbekistan — Oʻzbekiston Respublikasining Davlat Madhiyasi"                    ".txt",
    "Vanuatu — Yumi, Yumi, Yumi"                                                    ".txt",
    "Vatican City — Marche Pontificale"                                             ".txt",
    "Venezuela — Gloria al Bravo Pueblo"                                            ".txt",
    "Vietnam — Tiến Quân Ca"                                                        ".txt",
    "Yemen — National anthem of Yemen"                                              ".txt",
    "Zambia — National anthem of Zambia"                                            ".txt",
    "Zimbabwe — Simudzai Mureza wedu WeZimbabwe"                                    ".txt"
  };

  for (char const *const *name = names; name != names + (sizeof names / sizeof(char const*)); ++name) {
    std::FILE *const file = std::fopen(*name, "wb+");

    if (NULL == file)
      std::printf("\"%s\" not opened" "\r\n", *name);

    else {
      std::printf("\"%s\" opened at %08" PRIXPTR "\r\n", *name, reinterpret_cast<uintptr_t>(static_cast<void*>(file)));
      std::fclose(file);
    }
  }
}
